sudo: false

language: php

cache:
  directories:
    - $HOME/.composer/cache

env:
  global:
    - deps=""

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm
    - php: 7.0
  include:
    - php: 5.4
    - php: 5.5
    - php: 5.6
    - php: 7.0
    - php: hhvm

before_script:
  - if [ "$deps" = "" ]; then composer install; fi